language: node_js
node_js:
  - "7"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'create database travis_test;' -U postgres
  
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
   - npm run coverage
   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false